# Change these first
owner: ArmadaSoftware # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Armada Yazılım
    url: https://armadayazilim.com/
  - name: Armada Yazılım - 3dexperience
    url: https://3dexperience.armadayazilim.com/
  - name: Armada Yazılım - Blog
    url: https://blog.armadayazilim.com/
  - name: Armada Yazılım - Arex
    url: https://arex.armadayazilim.com/
  - name: Armada Yazılım - Proje
    url: https://proje.armadayazilim.com/
  - name: Armada Yazılım - DelmiaWorks
    url: https://delmiaworks.armadayazilim.com/
  - name: Armada Yazılım - ArmadaWorks
    url: https://armadaworks.net/
  - name: Maksimo
    url: https://maksimo.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.armadayazilim.com
  # baseUrl: /status
  logoUrl: https://www.armadayazilim.com/kaynak/icerikler/logo-armada.svg
  name: Armada Yazılım Uptime Status
  introTitle: "Armada Yazılım **Upptime** Monitor "
  introMessage:   
  navbar:
    - title: Status
      href: /
    - title: Armada Yazılım
      href: https://armadayazilim.com/
    - title: ArmadaWorks
      href: https://armadaworks.net/
    - title: Arex
      href: https://arex.armadayazilim.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
